name: docs
on:
  workflow_dispatch: { }
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
      - name: fetch tags
        run: git fetch --prune --unshallow --tags
      - name: log current tag
        run: git describe --tags
      - uses: actions/setup-node@v4
      - name: build
        run: |
          cd docs
          npm install
          npm run docs:build
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist
      - uses: actions/deploy-pages@v4
